### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith' - No Applet rendering

### ISSUE THREAD

**Issue by tott** [city41/mate-i3-applet#14]
I'd love to use the applet but when I try to add it to the panel I only receive the following error in the logs and no output.

`Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]: Traceback (most recent call last):
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/mate-i3-applet/matei3applet.py", line 6, in <module>
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     setup_logging()
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/mate-i3-applet/log.py", line 21, in setup_logging
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     delay=True,
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/python3.5/logging/handlers.py", line 202, in __init__
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/python3.5/logging/__init__.py", line 999, in __init__
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     self.baseFilename = os.path.abspath(filename)
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/python3.5/posixpath.py", line 358, in abspath
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     if not isabs(path):
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:   File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]:     return s.startswith(sep)
Nov 25 01:10:36 x330 org.mate.panel.applet.I3AppletFactory[2167]: AttributeError: 'PosixPath' object has no attribute 'startswith'
Nov 25 01:10:36 x330 dbus-daemon[2167]: Activated service 'org.mate.panel.applet.I3AppletFactory' failed: Process org.mate.panel.applet.I3AppletFactory exited with status 1
`

i3 version 4.15.0.1-262-gcf878da0 (2018-08-28, branch "gaps-next") © 2009 Michael Stapelberg and contributors
MATE Desktop Environment 1.20.3

**Comment by tott** [comment]
Nevermind - I figured it out - I was using python3.5 but these methods require python3.6. Once I upgraded things were working fine.

**Comment by city41** [comment]
Glad you got unblocked @tott 

I think it'd be good to not require python 3.6. I'm going to reopen this and when I get a chance I'll take a look.

At the very least, if 3.6 really is required, I will note that on the README.

Thanks for the report!

**Comment by city41** [comment]
This was fixed with the latest release
