### ISSUE TITLE
Namespace error on Debian 10

### ISSUE THREAD

**Issue by cbacott** [city41/mate-i3-applet#23]
So, I've installed this applet before without any problems. I just tried to install it on a new Debian 10 VM and I'm getting the following. I'm not sure what I'm missing that causes this. Do I need some other package to make this work?

`Uncaught exception occurred: Namespace MatePanelApplet not available
NoneType: None`

**Comment by vesch** [comment]
Hey!
I've installed Debian 10 on my tablet and faced the same error.
An installation of **gir1.2-matepanelapplet-4.0** package is what helped to me.

**Comment by cbacott** [comment]
Thanks, I'll try that tomorrow when I'm back at work and see if that resolves it.

**Comment by cbacott** [comment]
Worked perfectly. Thank you. Maybe adding that dependency to the README would be a good idea?

**Comment by city41** [comment]
thanks @vesch! I'll add this to the README.

**Comment by nealbrophy** [comment]
Just an FYI that I've successfully installed this on both _Fedora 32_ and _openSUSE Tumbleweed_. Thanks!
