### ISSUE TITLE
Support for resize mode

### ISSUE THREAD

**Issue by antoniotrkdz** [city41/mate-i3-applet#9]
It would be nice to have support for resize mode.
That is when you press $mod+r.
Thanks!

P.S.: Good job!

**Comment by city41** [comment]
I just released version 1.1.0 that adds mode support. This will show "resize" when in resize mode. It will also support any other modes you define in your i3 config.

To upgrade, download 1.1.0 from the releases page and run `sudo ./setup.py install && killall -9 mate-panel` as usual, it will overwrite the old version.

Don't forget to switch to gtk 3.0 in matei3panel.py if you are on a newer version of MATE.

**Comment by city41** [comment]
oops, I added a regression with this change. Version 1.1.1 fixes the regression

https://github.com/city41/mate-i3-applet/releases/tag/1.1.1
